---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "externaldns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "externaldns.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: {{ include "externaldns.name" . }}
      containers:
        - name: external-dns
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --txt-owner-id=external-dns
            - --source=service
            - --source=ingress
            - --provider=yandex
            - --yandex-folder={{ .Values.config.folder_id }}
            - --yandex-iam-key-file=/etc/kubernetes/iamkeyfile.json
            - --txt-prefix=external-dns-
            {{- range .Values.domainFilters }}
            - --domain-filter={{ . }}
            {{- end }}
          volumeMounts:
            - name: yandex-iam-key-file
              mountPath: /etc/kubernetes
              readOnly: true
      volumes:
        - name: yandex-iam-key-file
          secret:
            secretName: {{ include "externaldns.fullname" . }}
            items:
              - key: iamkeyfile.json
                path: iamkeyfile.json
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
